const planets = [{
    "id": 0,
    "name": "Solar System",
    "image": "./resources/images/solar_system.jpg",
    "desc": " There are many planetary systems like ours in the universe, with planets orbiting a host star. Our planetary system is named the 'solar' system because our Sun is named Sol, after the Latin word for Sun, 'solis,' and anything related to the Sun we call 'solar.' Our planetary system is located in an outer spiral arm of the Milky Way galaxy. Our solar system consists of our star, the Sun, and everything bound to it by gravity — the planets Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune, dwarf planets such as Pluto, dozens of moons and millions of asteroids, comets and meteoroids. Beyond our own solar system, we have discovered thousands of planetary systems orbiting other stars in the Milky Way.",
    "obrit_distance": "7.6 to 8.2 kiloparsec",
    "radius": "50,000 Astronomical Units",
    "volume": "Unknown",
    "mass": "Unknown",
    "density": "Unknown",
    "surface_gravity": "N/A",
    "escape_velocity": "Unknown",
    "rotation_period": "Unknown",
    "orbit_period": "Unknown",
    "mean_orbit_velocity": "240 km/s",
    "orbit_eccentricity": "Unknown",
    "equatorial_inclination": "N/A",
    "surface_temperature": "Unknown",
    "atmosphere": "N/A",
    "moons": "200+",
    "rings": "N/A"
}, {
    "id": 1,
    "name": "Sun",
    "image": "./resources/images/sun.jpg",
    "desc": "The Sun is a yellow dwarf star, a hot ball of glowing gases at the heart of our solar system. Its gravity holds the solar system together, keeping everything – from the biggest planets to the smallest particles of debris – in its orbit. The connection and interactions between the Sun and Earth drive the seasons, ocean currents, weather, climate, radiation belts and auroras. Though it is special to us, there are billions of stars like our Sun scattered across the Milky Way galaxy. The Sun has many names in many cultures. The Latin word for Sun is 'sol,' which is the main adjective for all things Sun-related: solar.",
    "obrit_distance": "N/A",
    "radius": "695,500 km",
    "volume": "1.409 x 10^18 km^3",
    "mass": "1.988 x 10^30 kg",
    "density": "14,080 g/cm^3",
    "surface_gravity": "274.0 m/s^2",
    "escape_velocity": "617.6 km/s",
    "rotation_period": "25.449 Earth Days",
    "orbit_period": "N/A",
    "mean_orbit_velocity": "N/A",
    "orbit_eccentricity": "N/A",
    "equatorial_inclination": "N/A",
    "surface_temperature": "5,505 °C",
    "atmosphere": "Hidrogen (90.9%), Helium (8.8%)",
    "moons": "N/A",
    "rings": "N/A"
}, {
    "id": 2,
    "name": "Mercury",
    "image": "./resources/images/mercury.jpg",
    "desc": "The smallest planet in our solar system and nearest to the Sun, Mercury is only slightly larger than Earth's Moon. From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as seven times brighter. Despite its proximity to the Sun, Mercury is not the hottest planet in our solar system – that title belongs to nearby Venus, thanks to its dense atmosphere.",
    "obrit_distance": "5.790 x 10^7 km",
    "radius": "2.439 x 10^3 km",
    "volume": "6.082 x 10^10 km^3",
    "mass": "3.301 x 10^23 kg",
    "density": "5.427 g/cm^3",
    "surface_gravity": "3.7 m/s^2",
    "escape_velocity": "4.25 x 10^3 m/s",
    "rotation_period": "58.646 Earth Days", 
    "orbit_period": "0.240 Earth Years", 
    "mean_orbit_velocity": "170,506 km/h",
    "orbit_eccentricity": "0.205",
    "equatorial_inclination": "0 degrees",
    "surface_temperature": "-173/427 °C",
    "atmosphere": "Unknown",
    "moons": "0",
    "rings": "No"
}, {
    "id": 3,
    "name": "Venus",
    "image": "./resources/images/venus.jpg",
    "desc": "Similar in size and structure to Earth, Venus has been called Earth's twin. These are not identical twins, however – there are radical differences between the two worlds. Venus has a thick, toxic atmosphere filled with carbon dioxide and it’s perpetually shrouded in thick, yellowish clouds of mostly sulfuric acid that trap heat, causing a runaway greenhouse effect. It’s the hottest planet in our solar system, even though Mercury is closer to the Sun. Venus has crushing air pressure at its surface – more than 90 times that of Earth – similar to the pressure you'd encounter a mile below the ocean on Earth. Venus was the first planet to be explored by a spacecraft – NASA’s Mariner 2 successfully flew by and scanned the cloud-covered world on Dec. 14, 1962. Since then, numerous spacecraft from the U.S. and other space agencies have explored Venus, including NASA’s Magellan, which mapped the planet's surface with radar. The former Soviet Union is the only nation to land on the surface of Venus to date, though the spacecraft did not survive long in the harsh environment.",
    "obrit_distance": "1.082 x 10^8 km",
    "radius": "6.051 km",
    "volume": "9.284 x 10^11",
    "mass": "4.867 x 10^24 kg",
    "density": "5.243 g/cm^3",
    "surface_gravity": "8.87 m/s^2",
    "escape_velocity": "3.729 x 10^4 km/h",
    "rotation_period": "-243.018 Earth Days",
    "orbit_period": "0.615 Earth Years",
    "mean_orbit_velocity": "1.260 x 10^5 km/h",
    "orbit_eccentricity": "0.006",
    "equatorial_inclination": "177.3 degrees (retrograde rotation)",
    "surface_temperature": "462 °C",
    "atmosphere": "Carbon Dioxide (96.5%), Nitrogen (3.5%)",
    "moons": "0",
    "rings": "No"
}, {
    "id": 4,
    "name": "Earth",
    "image": "./resources/images/earth.jpg",
    "desc": "Our home planet is the third planet from the Sun, and the only place we know of so far that’s inhabited by living things. While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal. The name Earth is at least 1,000 years old. All of the planets, except for Earth, were named after Greek and Roman gods and goddesses. However, the name Earth is a Germanic word, which simply means 'the ground.'",
    "obrit_distance": "1.496 x 10^8 km",
    "radius": "6.371 x 10^3 km",
    "volume": "1.083 x 10^12 km^3",
    "mass": "5.972 x 10^24 kg",
    "density": "5.513 g/cm^3 ",
    "surface_gravity": "9.80665 m/s^2",
    "escape_velocity": "40,284 km/h",
    "rotation_period": "0.997 Earth Days",
    "orbit_period": "1.000 Earth Years",
    "mean_orbit_velocity": "107,218 km/h",
    "orbit_eccentricity": "0.016",
    "equatorial_inclination": "23.439 ",
    "surface_temperature": "-88/58 °C",
    "atmosphere": "Nitrogen (78.1%), Oxygen (20.95%)",
    "moons": "1",
    "rings": "No"
}, {
    "id": 5,
    "name": "Mars",
    "image": "./resources/images/mars.jpg",
    "desc": "The fourth planet from the Sun, Mars is a dusty, cold, desert world with a very thin atmosphere. This dynamic planet has seasons, polar ice caps, canyons, extinct volcanoes, and evidence that it was even more active in the past. Mars is one of the most explored bodies in our solar system, and it's the only planet where we've sent rovers to roam the alien landscape. NASA currently has three spacecraft in orbit, and it has one rover and one lander on the surface. NASA launched the next-generation Perseverance rover to Mars on July 30, 2020. India and ESA have spacecraft in orbit above Mars. These robotic explorers have found lots of evidence that Mars was much wetter and warmer, with a thicker atmosphere, billions of years ago.",
    "obrit_distance": "2.279 x 10^8 km",
    "radius": "3.389 x 10^3 km",
    "volume": "1.631 x 10^11 km^3 ",
    "mass": "6.416 x 10^23 kg",
    "density": "3.934 g/cm^3",
    "surface_gravity": "3.71 m/s^2",
    "escape_velocity": "18,108 km/h",
    "rotation_period": "1.026 Earth Days",
    "orbit_period": "1.880 Earth Years",
    "mean_orbit_velocity": "86,677 km/h",
    "orbit_eccentricity": "0.093",
    "equatorial_inclination": "	25.2",
    "surface_temperature": "-153/+20 °C",
    "atmosphere": "Carbon Dioxide (95.1%), Nitrogen (2.59%), Argon (1.94%), Oxygen (0.26%). Carbon Monoxide (0.11%)",
    "moons": "2",
    "rings": "No"
}, {
    "id": 6,
    "name": "Jupiter",
    "image": "./resources/images/jupiter.jpg",
    "desc": "Jupiter has a long history surprising scientists—all the way back to 1610 when Galileo Galilei found the first moons beyond Earth. That discovery changed the way we see the universe. Fifth in line from the Sun, Jupiter is, by far, the largest planet in the solar system – more than twice as massive as all the other planets combined. Jupiter's familiar stripes and swirls are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. Jupiter’s iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years.",
    "obrit_distance": "7.783 x 10^8 km",
    "radius": "6.991 10^4 km",
    "volume": "1.431 x 10^15 km^3",
    "mass": "1.891 x 10^27 kg",
    "density": "1.326 g/cm^3",
    "surface_gravity": "24.79 m/s^2",
    "escape_velocity": "216,720 km/h",
    "rotation_period": "0.413 Earth Days",
    "orbit_period": "11.862	 Earth Years",
    "mean_orbit_velocity": "47,002 km/h",
    "orbit_eccentricity": "0.048",
    "equatorial_inclination": "3.1 degrees",
    "surface_temperature": "Unknown",
    "atmosphere": "Hydrogen (89.8%), Helium (10.2%)",
    "moons": "79",
    "rings": "Yes"
}, {
    "id": 7,
    "name": "Saturn",
    "image": "./resources/images/saturn.jpg",
    "desc": "Saturn is the sixth planet from the Sun and the second largest planet in our solar system. Adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings—made of chunks of ice and rock—but none are as spectacular or as complicated as Saturn's. Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium.",
    "obrit_distance": "1.426 x 10^9 km",
    "radius": "5.823 x 10^4 km",
    "volume": "8.271 x 10^14 km^3",
    "mass": "5.683 x 10^26 kg",
    "density": "0.687 g/cm^3",
    "surface_gravity": "10.44 m/s^2",
    "escape_velocity": "129,924 km/h",
    "rotation_period": "0.444 Earth Days",
    "orbit_period": "29.447 Earth Years",
    "mean_orbit_velocity": "34,701 km/h",
    "orbit_eccentricity": "0.053",
    "equatorial_inclination": "26.7 degrees",
    "surface_temperature": "Unknown",
    "atmosphere": "Hydrogen (96.5%), Helium (3.5%)",
    "moons": "83",
    "rings": "Yes"
}, {
    "id": 8,
    "name": "Uranus",
    "image": "./resources/images/uranus.jpg",
    "desc": "The first planet found with the aid of a telescope, Uranus was discovered in 1781 by astronomer William Herschel, although he originally thought it was either a comet or a star. It was two years later that the object was universally accepted as a new planet, in part because of observations by astronomer Johann Elert Bode. Herschel tried unsuccessfully to name his discovery Georgium Sidus after King George III. Instead the scientific community accepted Bode's suggestion to name it Uranus, the Greek god of the sky, as suggested by Bode.​",
    "obrit_distance": "2.870 x 10^9 km",
    "radius": "2.536 x 10^4 km",
    "volume": "6.833 x 10^13 km^3",
    "mass": "8.681 x 10^25 kg",
    "density": "1.270 g/cm3",
    "surface_gravity": "8.870 m/s^2",
    "escape_velocity": "76,968 km/h",
    "rotation_period": "-0.718 Earth Days",
    "orbit_period": "84.016 Earth Years",
    "mean_orbit_velocity": "24,477 km/h",
    "orbit_eccentricity": "0.047",
    "equatorial_inclination": "97.8 degrees (retrograde rotation)",
    "surface_temperature": "Unknown",
    "atmosphere": "Hydrogen (82.5%), Helium (15.2%), Methane (2.3%)",
    "moons": "27",
    "rings": "yes"

}, {
    "id": 9,
    "name": "Neptune",
    "image": "./resources/images/neptune.jpg",
    "desc": "Dark, cold and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet in our solar system. More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye and the first predicted by mathematics before its discovery. In 2011 Neptune completed its first 165-year orbit since its discovery in 1846. NASA's Voyager 2 is the only spacecraft to have visited Neptune up close. It flew past in 1989 on its way out of the solar system.",
    "obrit_distance": "4.498 x 10^9 km",
    "radius": "2.462 x 10^4 km",
    "volume": "6.252 x 10^13 km^3",
    "mass": "1.024 x 10^26 kg",
    "density": "1.638 g/cm^3",
    "surface_gravity": "11.150 m/s^2",
    "escape_velocity": "84,816 km/h",
    "rotation_period": "0.671 Earth Days",
    "orbit_period": "164.791 Earth Years",
    "mean_orbit_velocity": "19,566 km/h",
    "orbit_eccentricity": "0.008",
    "equatorial_inclination": "28.3 degrees",
    "surface_temperature": "Unknown",
    "atmosphere": "Hydrogen (80.0%), Helium (19.0%), Methane (1.0%)",
    "moons": "14",
    "rings": "Yes"
}]